# Generated by Django 4.2.16 on 2024-12-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0002_telescope'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='discovered_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
